### ISSUE TITLE
Layer display 

### ISSUE THREAD

**Issue by adam5zki** [Qrome/printer-monitor#107]
Would it be possible to include a screen (or show on an existing one, e.g. the remaining print time one) that shows the current layer # being printed and the total number of layers?

**Comment by Qrome** [comment]
I think I recall a request a long time ago about this.   Getting the layer information is actually quite complex.   It looks like it would require a plugin to be installed and running on the OctoPrint server, then apply the correct api request to get it.   
Plugin here:  https://github.com/OllisGit/OctoPrint-DisplayLayerProgress#rest---api

I don't plan on adding this.

**Comment by adam5zki** [comment]
I see.
