### ISSUE TITLE
Let PrinterMonitor find the Octoprint IP

### ISSUE THREAD

**Issue by wabbitguy** [Qrome/printer-monitor#11]
When Octoprint installs you always have to give it a name as it appears on the network, so I figured why not use it instead of a hard coded, sometimes prone to change, IP?

Let Printer Monitor do a scan at the startup, find the matching name that was used for the Octoprint install, then set the IP itself. Regardless of the router changes, printer monitor will always find Octoprint's IP.

Mel
----

Settings.h
String OctoPrintServer = "x.x.x.x"; // IP or Address of your OctoPrint Server (DO NOT include http://)
String OctoHostName = "DROOLER";// name of the octoprint install

printermonitor
void setup() {
findMDNS();// insert as very last line in setup(), go find Octoprint
}

void findMDNS() {
  // We now query our network for 'web servers' service
  // over tcp, and get the number of available devices
  int n = MDNS.queryService("http", "tcp");
  if (n == 0) {
    Serial.println("no services found");
  }
  else {
    for (int i = 0; i < n; ++i) {
      // Going through every available service,
      // we're searching for the one whose hostname
      // matches what we want, and then get its IP
      //Serial.println(MDNS.hostname(i));
      //Serial.println(MDNS.IP(i));
      //Serial.println(MDNS.port(i));
      if (MDNS.hostname(i) == OctoHostName) {
        OctoPrintServer = String(MDNS.IP(i));// shove in the IP of the octoprint instance
      }
    }
  }
}

**Comment by Qrome** [comment]
This will be a nice addition.  I will look at it closer here this week.

**Comment by Qrome** [comment]
Thanks Mel, I will start testing it later this week when I get some time.

**Comment by Qrome** [comment]
Mel, I have updated the dev branch of 1.5 with the MDNS -- it also includes the web ui configuration for this as well.  It seems to be working well for me.  I also have it check for the IP after saving the configuration if the user changes the hostname.    When you get time try it out:  https://github.com/Qrome/printer-monitor/tree/1.5

**Comment by wabbitguy** [comment]
I'll check it out tomorrow and let you know.

**Comment by wabbitguy** [comment]
Working perfectly here David!
