### ISSUE TITLE
More than one on a network, second is stuck on "Web Interface on"

### ISSUE THREAD

**Issue by bepstein111** [Qrome/printer-monitor#111]
I liked the first one so much, I set up a second for the workshop, but it appears that the second one won't show anything past "Web interface On, You May Connect to IP (local IP address) Port 80. No weather, no printer status, no clock, nothing. Just seems frozen. Anybody run into issues with more than one on a network?

**Comment by Qrome** [comment]
What pins did you connect the OLED to?   Also, did you enable 1M SPIFFS?

**Comment by bepstein111** [comment]
Yup that's my issue. Good call, thanks for the quick reply!
