### ISSUE TITLE
PCB Order alternatives

### ISSUE THREAD

**Issue by DerSeb90** [Qrome/printer-monitor#142]
Hi. First thanks for this awesome Project. I want to use the PCB from Etsy. I just need the PCB because i have enough wemos and displays. The shipping is much less if i Order the PCBs from pcbway. Is it possible to get the Gerber Files?

**Comment by Qrome** [comment]
DerSeb90 -- sorry, I won't be sharing the Gerber files for the custom PCB.  However if you want to purchase a few of them from me directly, I would be happy to send you some.   Thanks.

**Comment by DerSeb90** [comment]
Yes please contact me at stampernator@gmail.com
