### ISSUE TITLE
Firmware update page doesnt load

### ISSUE THREAD

**Issue by pingywon** [Qrome/printer-monitor#157]
Just for the sake of documentation at least, when I click Firmware Update it doesnt load. This is a really cool project and I hope someone picks it up and starts active development again, there a ton of things that could be done with this.

**Comment by Qrome** [comment]
Firmware update does work.   You must download the binary file you wish to load or create it first.
![image](https://user-images.githubusercontent.com/32021227/152801252-9d8a4802-0854-4271-a65d-cf7091bbe533.png)

When you see this page then click on the "Choose File" button... select the binary file you want to load, then click on the update button.

**Comment by pingywon** [comment]
> When you see this page then click on the "Choose File" button... select the binary file you want to load, then click on the update button.

Cant ever get to that page, thats what im saying. Tried in a few browsers, incognito and all that.  What am i missing?

**Comment by Qrome** [comment]
What do you get when you click on the link for the firmware update?   Is everything else working for you?   Do you know what version of the ESP8266 core you used to compile your build?  What version are you currently running?

**Comment by pingywon** [comment]
I just bought (from you id imagine) from Etsy. When I click on the firmware (which to be clear I dont need) the page just refreshes.  Everything else works great! version 3.0
