### ISSUE TITLE
add OTA authentification

### ISSUE THREAD

**Issue by c-ascha** [Qrome/printer-monitor#16]
hey, is it possible to add a authentication for the OTA flashing?

thank you!

**Comment by Qrome** [comment]
Yeah, looks to be easy.   I will add a variable in the Settings.h that will then set it the main code with something like this:

`ArduinoOTA.setPassword((const char *)"123");`

I will only set the password if there is a value in it.  I will let you know when I have a branch for you to test.

**Comment by Qrome** [comment]
I have added it to the 1.7 dev branch and it will be part of the final master release soon.   You can test it here:  https://github.com/Qrome/printer-monitor/tree/1.7
