### ISSUE TITLE
Display issue 

### ISSUE THREAD

**Issue by KSTV28** [Qrome/printer-monitor#163]
So I been fighting with this project for a few day's now where I said heck with it, I bought the Wemos Mini D2 and the HiLetgo 1.3" IIC I2C Serial 128x64 SSH1106 SSD1306 OLED LCD and when I go to the settings.h and do must uncomment #define DISPLAY_SH1106 in the Settings.h it still does the lines on the screen, All my wires on the Wemos Mini is correct when I go in and change the wording it turns the screen completely off and when I revert back it come's on with the lines or sometimes it has like tv static so I have no idea what is going on hopefully someone could help me figure this out cause I would like to get this to work.  
![IMG_5890](https://user-images.githubusercontent.com/73322561/192124072-6edd9503-120b-46a3-9350-58f158276f89.jpg)

**Comment by Qrome** [comment]
Are you sure you have the 1.3" version?  Is the web interface working?   Do the settings save?

**Comment by KSTV28** [comment]
I can post the amazon link to the screen I ordered that you had posted for the 1.3
https://www.amazon.com/dp/B01MRR4LVE?psc=1&ref=ppx_yo2ov_dt_b_product_details This is the screen that I bought that was listed in the post.

**Comment by Qrome** [comment]
The case you are showing there appears to be for the smaller display so you would comment out the SSH1106 driver on line 97 of the Settings.h file.

**Comment by KSTV28** [comment]
I went with the bigger screen the 1.3 and found a remix 3D model of the case for the bigger screen https://www.thingiverse.com/thing:2884823

**Comment by Qrome** [comment]
Is the Web interface working?  Does it save and store settings?

**Comment by KSTV28** [comment]
The web interface is working

**Comment by KSTV28** [comment]
I see stuff is moving on the screen like time and what not but it still has those white lines moving

**Comment by Qrome** [comment]
Have you tried loading the pre-compiled binary for the 1106 display?   https://github.com/Qrome/printer-monitor/blob/master/printermonitor.ino.d1_mini_SH1106.bin

**Comment by KSTV28** [comment]
https://user-images.githubusercontent.com/73322561/192124826-c8171eba-0218-478e-89cf-17832dfa5a24.mov

**Comment by KSTV28** [comment]
I have not tried that yet
how do I compile that

**Comment by Qrome** [comment]
you can load it through the web interface

**Comment by KSTV28** [comment]
under firmware update?

**Comment by KSTV28** [comment]
also what is the main login and password or do I have to setup a custom one?

**Comment by Qrome** [comment]
user: admin 
password:   password

This is the same as the web interface

**Comment by KSTV28** [comment]
when I try to login to the web interface its brings up an error must to be something on my end
The connection was reset when i did the user as admin and password so must be my end most likely.

**Comment by Qrome** [comment]
have you been able to change and save any settings at all ever?   
If not, then make sure you compile it with allocation for the file system to create the configuration settings on it.
![image](https://user-images.githubusercontent.com/32021227/192125632-4eaf2828-9b63-4df9-8c99-76f122026f37.png)

**Comment by KSTV28** [comment]
so I need the flash size to be 4MB (FS:2MB and not the 1MB

**Comment by KSTV28** [comment]
same thing This site can’t be reached The connection was reset ugh this getting on my nerves

**Comment by KSTV28** [comment]
Dude thank you so much after I updated the firmware to the printermonitor.ino.d1_mini_SH1106.bin it works nomrally thank you very much

**Comment by KSTV28** [comment]
now a other question how can I change the time from UTC to CST

**Comment by Qrome** [comment]
Looks like you may not have had the right library loaded for the display when you compiled it.
