### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by ArcAIN6** [Qrome/printer-monitor#166]
...

**Comment by ArcAIN6** [comment]
....

**Comment by Qrome** [comment]
@ArcAIN6 -- not sure what you are looking for.  Sounds like you had an issue with the code.  If you want help, post it.  As for your comments, it compiles with all the latest libraries except the 1306 display.   Also, you don't need to use the settings.h as all the settings are stored using the web interface.   The project works.   Do you need help?   Other than asking if it is dead?  If you looked at some of the posts, there are people still building it.

**Comment by Qrome** [comment]
I closed the issue created hear because it was simply a statement of your frustration.

**Comment by ArcAIN6** [comment]
...
