### ISSUE TITLE
HTTP/1.1 403 FORBIDDEN

### ISSUE THREAD

**Issue by eboston** [Qrome/printer-monitor#19]
I can't seem to get the configuration right.  I keep getting the forbidden error.  There are a couple new fields in the config that was not in the video I was watching.  The video was 1.2 and this is 1.7.   The API key and IP address are correct.  How critical is the host name, OctoPrint User/Password?  I have tried my main username/password without success and even added another account, but with no luck.

**Comment by eboston** [comment]
Resolved it.  The host name entry was causing the problem.  Once I removed it, it connected right up.

**Comment by Qrome** [comment]
Yeah, only use the host name field if your IP changes.
