### ISSUE TITLE
configuration page clears www_password

### ISSUE THREAD

**Issue by jeffeb3** [Qrome/printer-monitor#26]
The configuration page of the web interface correctly saves the www_password when the save button is pressed, but when the page loads the next time, the field is cleared again (which I think is also the right choice). The trouble is that if you hit save again, to save another setting, the password gets cleared. And then you're locked out, unless you enter a blank password in the authentication dialog.

I was thinking that you could either:
a) check for an empty password, and choose not to set www_password if it's empty, but someone might want an empty password, IDK.
b) set the field to something weird, like notapassword and then if the form comes back as notapassword, then you don't set www_password. Then you wouldn't be able to have "notapassword" as your password, but maybe it's OK to make someone mad?

**Comment by Qrome** [comment]
I have attempted to recreate this issue in both Chrome and Firefox -- I am not able to.   I am using V2.0 of the Printer Monitor and I do not get the password field blanked out.

My testing:

1.  Go to Configuration page... authenticate
2.  Check user 24 hour clock and save (redirects to home)
3.  Enter Configuration page and scroll down and see password field still populated.

Is it possible that your password manager is auto populating and blanking it out?   I do not see an issue here and we are on V2.0 and nobody else I know running this have had any issue.

When entering a bug for any software, please provide as much information as possible.   Version numbers and detailed steps.   Thanks.
