### ISSUE TITLE
Show weather when print complete?

### ISSUE THREAD

**Issue by mifbody** [Qrome/printer-monitor#27]
Hi there,

Would it be possible to show the weather when the print is complete instead of only when it's off-line? I leave octoprint on-line even when I'm not printing so with the current config the weather would never show. It would be awesome if - after the print is finished - it switched to the weather display.

**Comment by Qrome** [comment]
Thanks for the request.   I leave OctoPrint on all the time as well.  It is when I turn off the printer that it rolls to display the clock and weather.   If I leave a print over night, I want to look at the monitor and see how long it took to print and so on.   

You could easily implement this on your own local version, however, I do not plan on making this change in the master release.
