### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by AlexanderDNye** [Qrome/printer-monitor#37]
When trying to compile I get this error. Any ideas?

`Arduino: 1.6.8 (Windows 10), Board: "WeMos D1 R1, 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void setup()':

printermonitor:172: error: 'readSettings' was not declared in this scope

   readSettings();

                ^

printermonitor:256: error: 'displayPrinterStatus' was not declared in this scope

     server.on("/", displayPrinterStatus);

                    ^

printermonitor:257: error: 'handleSystemReset' was not declared in this scope

     server.on("/systemreset", handleSystemReset);

                               ^

printermonitor:258: error: 'handleWifiReset' was not declared in this scope

     server.on("/forgetwifi", handleWifiReset);

                              ^

printermonitor:259: error: 'handleUpdateConfig' was not declared in this scope

     server.on("/updateconfig", handleUpdateConfig);

                                ^

printermonitor:260: error: 'handleUpdateWeather' was not declared in this scope

     server.on("/updateweatherconfig", handleUpdateWeather);

                                       ^

printermonitor:261: error: 'handleConfigure' was not declared in this scope

     server.on("/configure", handleConfigure);

                             ^

printermonitor:262: error: 'handleWeatherConfigure' was not declared in this scope

     server.on("/configureweather", handleWeatherConfigure);

                                    ^

printermonitor:263: error: 'redirectHome' was not declared in this scope

     server.onNotFound(redirectHome);

                       ^

printermonitor:289: error: 'flashLED' was not declared in this scope

   flashLED(5, 500);

                  ^

printermonitor:290: error: 'findMDNS' was not declared in this scope

   findMDNS();  //go find Octoprint Server by the hostname

            ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void findMDNS()':

printermonitor:315: error: 'writeSettings' was not declared in this scope

       writeSettings(); // update the settings

                     ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void loop()':

printermonitor:326: error: 'getMinutesFromLastRefresh' was not declared in this scope

   if((getMinutesFromLastRefresh() >= minutesBetweenDataRefresh) || lastEpoch == 0) {

                                 ^

printermonitor:327: error: 'getUpdateTime' was not declared in this scope

     getUpdateTime();

                   ^

printermonitor:346: error: 'checkDisplay' was not declared in this scope

   checkDisplay(); // Check to see if the printer is on or offline and change display.

                ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleSystemReset()':

printermonitor:382: error: 'redirectHome' was not declared in this scope

     redirectHome();

                  ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleUpdateWeather()':

printermonitor:395: error: 'writeSettings' was not declared in this scope

   writeSettings();

                 ^

printermonitor:397: error: 'checkDisplay' was not declared in this scope

   checkDisplay();

                ^

printermonitor:399: error: 'redirectHome' was not declared in this scope

   redirectHome();

                ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleUpdateConfig()':

printermonitor:421: error: 'writeSettings' was not declared in this scope

   writeSettings();

                 ^

printermonitor:424: error: 'checkDisplay' was not declared in this scope

   checkDisplay();

                ^

printermonitor:426: error: 'redirectHome' was not declared in this scope

   redirectHome();

                ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleWifiReset()':

printermonitor:435: error: 'redirectHome' was not declared in this scope

   redirectHome();

                ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleWeatherConfigure()':

printermonitor:454: error: 'getHeader' was not declared in this scope

   html = getHeader();

                    ^

printermonitor:474: error: 'getFooter' was not declared in this scope

   html = getFooter();

                    ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void handleConfigure()':

printermonitor:494: error: 'getHeader' was not declared in this scope

   html = getHeader();

                    ^

printermonitor:527: error: 'getFooter' was not declared in this scope

   html = getFooter();

                    ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void displayMessage(String)':

printermonitor:542: error: 'getHeader' was not declared in this scope

   String html = getHeader();

                           ^

printermonitor:545: error: 'getFooter' was not declared in this scope

   html = getFooter();

                    ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'String getHeader()':

printermonitor:564: error: too many arguments to function 'String getHeader()'

   return getHeader(false);

                         ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino:563:8: note: declared here

 String getHeader() {

        ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void displayPrinterStatus()':

printermonitor:659: error: 'zeroPad' was not declared in this scope

     html += "Est. Print Time Left: " + zeroPad(hours) + ":" + zeroPad(minutes) + ":" + zeroPad(seconds) + "<br>";

                                                     ^

printermonitor:689: error: 'getSpeedSymbol' was not declared in this scope

       html += weatherClient.getWind(0) + " <span class='w3-tiny'>" + getSpeedSymbol() + "</span> Wind<br>";

                                                                                     ^

printermonitor:693: error: 'getTempSymbol' was not declared in this scope

       html += weatherClient.getTempRounded(0) + getTempSymbol(true) + "<br>";

                                                                   ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void configModeCallback(WiFiManager*)':

printermonitor:727: error: 'flashLED' was not declared in this scope

   flashLED(20, 50);

                  ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void drawScreen2(OLEDDisplay*, OLEDDisplayUiState*, int16_t, int16_t)':

printermonitor:765: error: 'zeroPad' was not declared in this scope

   String time = zeroPad(hours) + ":" + zeroPad(minutes) + ":" + zeroPad(seconds);

                              ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void drawScreen3(OLEDDisplay*, OLEDDisplayUiState*, int16_t, int16_t)':

printermonitor:782: error: 'zeroPad' was not declared in this scope

   String time = zeroPad(hours) + ":" + zeroPad(minutes) + ":" + zeroPad(seconds);

                              ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void drawWeather(OLEDDisplay*, OLEDDisplayUiState*, int16_t, int16_t)':

printermonitor:802: error: 'getTempSymbol' was not declared in this scope

   display->drawString(0 + x, 0 + y, weatherClient.getTempRounded(0) + getTempSymbol());

                                                                                     ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'String getTempSymbol()':

printermonitor:813: error: too many arguments to function 'String getTempSymbol()'

   return getTempSymbol(false);

                             ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino:812:8: note: declared here

 String getTempSymbol() {

        ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void drawHeaderOverlay(OLEDDisplay*, OLEDDisplayUiState*)':

printermonitor:874: error: 'drawRssi' was not declared in this scope

   drawRssi(display);

                   ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void drawClockHeaderOverlay(OLEDDisplay*, OLEDDisplayUiState*)':

printermonitor:891: error: 'drawRssi' was not declared in this scope

   drawRssi(display);

                   ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void writeSettings()':

printermonitor:946: error: 'readSettings' was not declared in this scope

   readSettings();

                ^

G:\Documents\Arduino\printer-monitor-master\printer-monitor-master\printermonitor\printermonitor.ino: In function 'void checkDisplay()':

printermonitor:1062: error: 'enableDisplay' was not declared in this scope

     enableDisplay(true);

                       ^

printermonitor:1074: error: 'enableDisplay' was not declared in this scope

     enableDisplay(false);

                        ^

printermonitor:1080: error: 'enableDisplay' was not declared in this scope

       enableDisplay(true);

                         ^

exit status 1
'readSettings' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by Qrome** [comment]
Wow -- well... do you have all the files that go with the printermonitor.ino file in the same directory.   Do you have all the supporting library files installed and in the path.   

Please take a look at the detailed video done by Chris Riley.  It has lots of good information on making sure you have everything setup correctly to compile the code.   https://youtu.be/Rm-l1FSuJpI

**Comment by wabbitguy** [comment]
Windows Arduino 1.6.8 is more than two years out of date as well (March 2016). A lot has changed since those days in the IDE as well as supporting libraries.

**Comment by AlexanderDNye** [comment]
Lol wow, so I'll update my IDE and try again.

And that's actually the video I've been using.

**Comment by Qrome** [comment]
Ahhh, good catch guys.   Let us know how it goes.

**Comment by wabbitguy** [comment]
Yeah, been bitten myself a few times with a few versions behind...LOL

Remember to update your libraries and boards as well. That'll keep everything happier...:-)

**Comment by AlexanderDNye** [comment]
Ok, so I've gotten a little bit further. 

It seemed that some of the libraries like the ArduinoJson didn't like to be at their latest build. I ended up closely looking at what versions of each library Chris used in his video and used that.

Now its compiling but I'm getting another error.

`Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Archiving built core (caching) in: C:\Users\alexa\AppData\Local\Temp\arduino_cache_476758\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_921600_f61d43f952a7d3551d2738c9a0d3b1b6.a
Sketch uses 471185 bytes (45%) of program storage space. Maximum is 1044464 bytes.
Global variables use 49112 bytes (59%) of dynamic memory, leaving 32808 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by AlexanderDNye** [comment]
Fixed by resetting the D1 mini.

Thanks for all of everyone's help.
