### ISSUE TITLE
Show currect Z position

### ISSUE THREAD

**Issue by tbergman88** [Qrome/printer-monitor#41]
I would like to add the ability to see the current Z position during a print. I often need this when awaiting a color change or just to see how things are moving along.
I looked at the Octoprint API and it looks like this is only available with a push request from Octoprint, not as something I can query. 
Can this be added or can someone advise me on how?

Thanks

**Comment by Qrome** [comment]
Short answer, probably no.   The push updates require the use of SocksJS.  Probably not going to be included any time soon.
