### ISSUE TITLE
Time Remaining/Printing Time over 24h not supported

### ISSUE THREAD

**Issue by SillyHats** [Qrome/printer-monitor#43]
When the Printing Time and/or Time remaining is over 24 hours it only shows the remainder of hours above any 24/48/72 hour full days. On a long print currently running I have Print time of 54:37:15 shown on octoprint web interface with 6:37:45 on the print monitor. The remaining time is now under 24 hours, but a similar effect was happening with the Remaining Time when it was 25:15:10 on the web/telegram plugin it showed 1:15:10 on the printer monitor.

How can the code be updated to accommodate times greater than 24 hours?

**Comment by Qrome** [comment]
I think we may have to display days.   I will look into it.   Thanks!

**Comment by Qrome** [comment]
This is being addressed in release 2.3 -- it is in dev branch now.   Thanks.

**Comment by Qrome** [comment]
This is now released in version 2.3
