### ISSUE TITLE
Allow different Octoprint port

### ISSUE THREAD

**Issue by brunosso** [Qrome/printer-monitor#46]
I edit the OctoPrintPort value in settings.h but don't work. I have Octoprint listening on port 8000

**Comment by Qrome** [comment]
Editing the settings.h AFTER it has already been loaded will NOT change your port.  You must use the web interface to change settings after it is loaded.  Or you have to perform a full chip erase when loading it.   This is mentioned in the readme.md file.   I hope that helps.

**Comment by brunosso** [comment]
I change the settings.h before the first upload to the Wemos.. BTW if i change by the web interface the port is stuck at value 80
