### ISSUE TITLE
Octoprint port won't change

### ISSUE THREAD

**Issue by brunosso** [Qrome/printer-monitor#47]
Like the https://github.com/Qrome/printer-monitor/issues/46

I change the settings.h before the first upload to the Wemos.. BTW if i change by the web interface the port is stuck at value 80

**Comment by Qrome** [comment]
Once the firmware is loaded you change these values in the web interface -- changing them again in the settings.h file will not work.   This is listed in the Readme.md file.

**Comment by brunosso** [comment]
i don't know how i told you!

If i change the port in the web interface stay always 80 as value!
