### ISSUE TITLE
Hostname for OTA

### ISSUE THREAD

**Issue by wabbitguy** [Qrome/printer-monitor#5]
I like using the hostname for OTA, otherwise in the Arduino IDE port menu it shows up as a ESP8266xxxx....

In the Setup(), I added the line:

ArduinoOTA.setHostname((const char *)hostname.c_str());// added line
ArduinoOTA(begin);// original line

In the Arduino port menu it now shows "Octomon at xxx.xxx.xxx.xxx" or whatever the hostname is set to. Handy in the event you have a workshop full of ESP8266's...:-)

Mel

**Comment by Qrome** [comment]
Thanks, I will add this.  This will be nice for the OTA people out there.  :)

**Comment by Qrome** [comment]
I have added it to the branch 1.4 -- it will be the next release.   Thanks.  I will close this item.
