### ISSUE TITLE
JSON issue

### ISSUE THREAD

**Issue by icewraithuk** [Qrome/printer-monitor#50]
Hi,

I'm getting this issue - 

```
sketch/OpenWeatherMapClient.cpp: In member function 'void OpenWeatherMapClient::updateWeather()':
OpenWeatherMapClient.cpp:78:3: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer(bufferSize);

```

Apparently it's been seen before but was "fixed" Anyone know how did you fix it please?

**Comment by Qrome** [comment]
Yeah, this has been covered a few times as well as in the Readme.md file.   You need to install the correct version of ArduinoJson -- do not use the 6.X Beta version as it has breaking changes in it and is still BETA.   Use the 5.X (latest as listed in the readme).
