### ISSUE TITLE
AP using Hostname

### ISSUE THREAD

**Issue by wabbitguy** [Qrome/printer-monitor#6]
When the available wifi network isn't available, the default 8266 name is ESP + chip ID, and if you have a shop full of 8266's kind of hard to remember all the chip ID's.

 //or use this for auto generated name ESP + ChipID
  wifiManager.autoConnect();

Suggest a change to use the user defined Hostname instead:

 // wifiManager.autoConnect();// old line
  if (!wifiManager.autoConnect(HOSTNAME)) {// new addition
    delay(3000);
    WiFi.disconnect(true);
    ESP.reset();
    delay(5000);
  }
//

Hostname will then show up as the access point.

Mel

**Comment by Qrome** [comment]
Thanks, I added the custom hostname for the WifiManager.   I have also added a display screen to instruct the user what to do when it is in AP mode.
