### ISSUE TITLE
OpenWeatherMap Multilingual

### ISSUE THREAD

**Issue by Flintstones1508** [Qrome/printer-monitor#61]
It's possible to add Multilingual support for OpenWeatherMap
I have try and it works on French

add &lang=xx on apiGetData
and add xx on setting.h with this choice : 
Arabic - ar, Bulgarian - bg, Catalan - ca, Czech - cz, German - de, Greek - el, English - en, Persian (Farsi) - fa, Finnish - fi, French - fr, Galician - gl, Croatian - hr, Hungarian - hu, Italian - it, Japanese - ja, Korean - kr, Latvian - la, Lithuanian - lt, Macedonian - mk, Dutch - nl, Polish - pl, Portuguese - pt, Romanian - ro, Russian - ru, Swedish - se, Slovak - sk, Slovenian - sl, Spanish - es, Turkish - tr, Ukrainian - ua, Vietnamese - vi, Chinese Simplified - zh_cn, Chinese Traditional - zh_tw.

Thanks for your work

**Comment by Qrome** [comment]
Well, this is a little frustrating.   I just went through and added the Weather Language support to my dev branch 2.3 and the JSON response does have certain fields that come back in the specified language, however, the field we use for the printer monitor display comes from weather.main data field and is the general condition -- this is something like "Sunny", "Rain", or "Clouds" -- well it looks like those always come back in English despite the specified language to the Weather Service.  The Description field does come back in the specified language:

Clouds (Überwiegend bewölkt)

However, this only displays on the web interface.   The area we have to work with on the Print Monitor display is very small so I chose to display the weather.main (condition) as it was always one word.   
I will push my dev branch to 2.3 -- you can pull it down and check it out, but it is not going to change anything on the Printer Monitor.   I even added the web interface under the weather section for changing the language.

https://github.com/Qrome/printer-monitor/tree/2.3

**Comment by Qrome** [comment]
This was added to version 2.3 -- however it only displays the language in the web interface.  Sorry.
