### ISSUE TITLE
Question: Show image from camera

### ISSUE THREAD

**Issue by dtiger1138** [Qrome/printer-monitor#73]
I just came across this, and was wondering if it's possible to have the monitor display an image from the camera. It might be useful to make sure the print is not going haywire, especially if you are in another area of your home and can't keep looking in on it.

**Comment by easytarget** [comment]
The displays used by this are only 128x96 pixels, in a few shades of monochrome. It would make it difficult to see anything meaningful.
An old mobile phone + touchUI + charging lead will always be a far better option for a portable video monitor.

**Comment by Qrome** [comment]
This won't be happening.
