### ISSUE TITLE
Display weather and clock

### ISSUE THREAD

**Issue by marekmeli** [Qrome/printer-monitor#85]
Is it possible to display both weather and clock (side by side or in cycles) by enabling them at the same time? I have no way of testing now.
Thank you for your amazing job and excellent user support.

**Comment by Qrome** [comment]
Yes, if you build the double wide, it will display the Clock and Temp at the same time.

https://www.thingiverse.com/thing:2989552

![ec44744ab36e8094482d9fd6d0f703b8_preview_featured](https://user-images.githubusercontent.com/32021227/56932647-621b2f00-6a99-11e9-8328-32ca6127e493.jpeg)

**Comment by Qrome** [comment]
Not sure what you mean, it switches between clock and weather every 10 seconds or so when it isn't printing.

**Comment by marekmeli** [comment]
Thank you, that's exactly the information I needed.
